# Generated by Django 5.2.9 on 2026-08-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100)),
                ('welcome_message', models.TextField(help_text='The first message the bot sends when the chat opens')),
                ('system_prompt', models.TextField(help_text="The full system prompt that defines the bot's knowledge and behaviour")),
                ('message_limit', models.PositiveIntegerField(default=50, help_text='Maximum number of messages a user can send (50 for individual, 150 for bundles)')),
                ('access_days', models.PositiveIntegerField(default=60, help_text='Number of days access is granted after purchase (60 for individual, 90 for bundles)')),
                ('model', models.CharField(choices=[('claude-haiku-4-5-20251001', 'Haiku 4.5 — recommended'), ('claude-sonnet-4-5', 'Sonnet — more capable')], default='claude-haiku-4-5-20251001', help_text='Which Claude model this coach uses. Haiku keeps running costs down and is well suited to answering from a workbook PDF.', max_length=64)),
                ('max_tokens', models.PositiveIntegerField(default=1000, help_text='Maximum length of each reply, in tokens. Lower = shorter, cheaper answers.')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='BotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Momentum Your Way Workbook', max_length=100)),
                ('knowledge_file', models.FileField(help_text='PDF file only', upload_to='bot_knowledge/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order in which files are added to the prompt')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bot_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to='bots.botproduct')),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list, help_text='Full conversation history as a list of role/content dicts')),
                ('quiz_answers', models.JSONField(blank=True, default=dict, help_text='Stored quiz question and answer pairs')),
                ('saved_goal', models.TextField(blank=True, help_text='The goal text the user chose to save to the tracker')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversations', to=settings.AUTH_USER_MODEL)),
                ('bot_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='bots.botproduct')),
            ],
            options={
                'verbose_name_plural': 'Bot Conversations',
                'unique_together': {('user', 'bot_product')},
            },
        ),
        migrations.CreateModel(
            name='BotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('bonus_messages', models.PositiveIntegerField(default=0, help_text='Extra messages granted manually (e.g. top-up purchases)')),
                ('access_expires', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_accesses', to=settings.AUTH_USER_MODEL)),
                ('bot_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='bots.botproduct')),
            ],
            options={
                'verbose_name_plural': 'Bot Accesses',
                'unique_together': {('user', 'bot_product')},
            },
        ),
    ]
