# Generated by Django 6.0 on 2025-12-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_bar_text', models.CharField(blank=True, help_text='Optional announcement message shown at the top of the dashboard.', max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
