# Generated by Django 5.2.9 on 2026-01-30 16:15

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Used in the page URL, e.g. /policies/terms/', unique=True)),
                ('page_type', models.CharField(choices=[('doc', 'Documentation'), ('policy', 'Policy')], max_length=10)),
                ('content', tinymce.models.HTMLField(help_text='Main page content. You can use headings, lists, and links.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category for grouping related documentation pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='infopages.category')),
            ],
            options={
                'verbose_name': 'Info Page',
                'verbose_name_plural': 'Info Pages',
                'ordering': ['page_type', 'title'],
            },
        ),
    ]
