# Generated by Django 5.2.9 on 2026-08-22 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('oto_seen_at', models.DateTimeField(blank=True, help_text='When the one-time offer was first shown to this user. Set once; ensures the offer is strictly one-time.', null=True)),
                ('favourite_products', models.ManyToManyField(blank=True, related_name='favorited_by', to='shop.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
