# Generated by Django 6.0 on 2025-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberresource',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Designates whether the user's email or identity has been verified."),
        ),
    ]
