# Generated by Django 6.0 on 2025-12-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberresource_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberresource',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
