# Generated by Django 5.2.9 on 2026-08-22 14:19

import django.db.models.deletion
import tinymce.models
import todianedev.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10 for 10%) or fixed amount in pounds (e.g. 5 for £5).', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Max total uses. Leave blank for unlimited.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('minimum_order_pence', models.PositiveIntegerField(default=0, help_text='Minimum cart total (in pence) required for this coupon.')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_digital_withdrawal_consent', models.BooleanField(default=False, help_text='Show the EU/UK digital withdrawal consent checkbox at checkout.')),
                ('digital_withdrawal_consent_text', models.CharField(default='I understand and agree that by completing this purchase I am requesting immediate access to digital content, and I therefore waive my right to withdraw from this contract under the EU/UK Consumer Rights Act (14-day cooling-off period).', max_length=500)),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, default='', help_text='Google Analytics measurement ID, e.g. G-XXXXXXXXXX.', max_length=30, verbose_name='Google Analytics ID')),
                ('google_search_console_verification', models.CharField(blank=True, default='', help_text='Verification token from Google Search Console meta tag.', max_length=255, verbose_name='GSC Verification Token')),
                ('og_image', models.ImageField(blank=True, help_text='Default Open Graph image (1200x630 px recommended).', null=True, upload_to='site/og/', verbose_name='Default OG Image')),
                ('facebook_app_id', models.CharField(blank=True, default='', help_text='Facebook App ID for Open Graph fb:app_id tag.', max_length=50, verbose_name='Facebook App ID')),
                ('currency_code', models.CharField(choices=[('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='GBP', max_length=3, verbose_name='Currency Code')),
                ('currency_symbol', models.CharField(default='£', max_length=5, verbose_name='Currency Symbol')),
                ('active_theme', models.CharField(choices=[('classic', 'Classic — default site design'), ('editorial', 'Editorial — warm tones, serif headings, magazine layout'), ('minimal', 'Minimal — clean black & white, Substack-style'), ('spotlight', 'Spotlight — featured products over a clean minimal feed')], default='classic', help_text='Choose the visual theme for the blog and shop. Classic uses your default design. Changes apply immediately.', max_length=20, verbose_name='Site Theme')),
                ('sidebar_heading', models.CharField(blank=True, default='Featured Products', help_text='Heading shown above the products sidebar on blog pages.', max_length=100, verbose_name='Blog Sidebar Heading')),
                ('sidebar_product_count', models.PositiveSmallIntegerField(default=5, help_text='Number of featured products to show in the blog sidebar.', verbose_name='Blog Sidebar Product Count')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_intent_id', models.CharField(blank=True, max_length=250)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=50)),
                ('coupon_discount_pence', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GuestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_details', to='shop.order')),
            ],
            options={
                'verbose_name_plural': 'Guest Details',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid_pence', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=130, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('section_description', models.TextField(blank=True, null=True)),
                ('long_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('download', 'Digital Download'), ('tool', 'Hosted Tool')], default='download', max_length=20)),
                ('number_of_pages', models.PositiveIntegerField(blank=True, help_text='Number of pages for digital downloads', null=True)),
                ('status', models.CharField(choices=[('publish', 'Published'), ('soon', 'Coming Soon'), ('full', 'Fully Booked'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('external_image_url', models.URLField(blank=True, help_text='External URL for product image (jpg/png only)', max_length=500, null=True)),
                ('external_preview_url', models.URLField(blank=True, help_text='External URL for preview file (PDF only)', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_pence', models.PositiveIntegerField(help_text='Price in pence')),
                ('sale_price_pence', models.PositiveIntegerField(blank=True, help_text='Sale price in pence', null=True)),
                ('price_per_hour', models.PositiveIntegerField(blank=True, help_text='Coaching price per hour in pence', null=True)),
                ('files', models.FileField(blank=True, help_text='Upload a PDF or ZIP file. Use ZIP for bundles.', null=True, storage=todianedev.storage.SecureFileStorage(), upload_to='products/files/')),
                ('preview_file', models.FileField(blank=True, null=True, storage=todianedev.storage.PublicMediaStorage(), upload_to='products/previews/')),
                ('preview_image', models.ImageField(blank=True, null=True, storage=todianedev.storage.PublicMediaStorage(), upload_to='products/images/')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube or Vimeo URL to display on the product page', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload a short MP4 file to display as product video', null=True, storage=todianedev.storage.PublicMediaStorage(), upload_to='products/videos/')),
                ('download_limit', models.PositiveIntegerField(default=5)),
                ('featured', models.BooleanField(default=False)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
                ('hosted_tool', models.OneToOneField(blank=True, help_text="Optional: attach a Hosted Tool to sell it as this product. Only tools set to 'Paid' can be selected here. Buyers reach the live tool from their downloads area, and the tool's public page becomes purchase-only. Leave blank for a normal file download.", limit_choices_to={'access': 'paid'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='tools.hostedtool')),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product'),
        ),
        migrations.CreateModel(
            name='OrderBump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Special One-Time Offer!', help_text='Bold headline shown on the bump box.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short pitch for why the customer should add this.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order if multiple bumps are active.')),
                ('bump_product', models.ForeignKey(help_text='The product being offered as the bump add-on.', on_delete=django.db.models.deletion.CASCADE, related_name='order_bumps', to='shop.product')),
                ('trigger_product', models.ForeignKey(blank=True, help_text='Only show this bump when this product is in the cart. Leave blank to always show.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_bump_triggers', to='shop.product')),
            ],
            options={
                'verbose_name': 'Order Bump',
                'verbose_name_plural': 'Order Bumps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OneTimeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Tick to show the one-time offer to eligible users on their next login.')),
                ('title', models.CharField(default='', help_text="Name of what they're buying (shown as the item title).", max_length=200)),
                ('price_pence', models.PositiveIntegerField(default=700, help_text='Price they pay, in pence (e.g. 700 = £7.00).')),
                ('compare_at_pence', models.PositiveIntegerField(blank=True, help_text="Optional 'normal' price in pence, shown with a line through it for contrast.", null=True)),
                ('file', models.FileField(blank=True, help_text='The downloadable file (PDF or ZIP) the buyer receives. Upload it here.', null=True, storage=todianedev.storage.SecureFileStorage(), upload_to='products/files/')),
                ('image', models.ImageField(blank=True, help_text='Optional image shown alongside the offer.', null=True, storage=todianedev.storage.PublicMediaStorage(), upload_to='products/images/')),
                ('download_limit', models.PositiveIntegerField(default=5, help_text='How many times the buyer can download the file.')),
                ('headline', models.CharField(default='A one-time offer, just for you', max_length=200)),
                ('subheadline', models.CharField(blank=True, default='', max_length=300)),
                ('body', tinymce.models.HTMLField(blank=True, help_text='Sales pitch shown under the headline.')),
                ('button_text', models.CharField(default='Yes, add this to my account', max_length=80)),
                ('decline_text', models.CharField(default='No thanks, take me to my dashboard', max_length=80)),
                ('show_timer', models.BooleanField(default=False, help_text='Show a countdown timer on the offer page.')),
                ('timer_minutes', models.PositiveIntegerField(default=15, help_text='Countdown length in minutes (visual urgency only).')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('included_products', models.ManyToManyField(blank=True, help_text="Tick the products this offer includes. On purchase the buyer gets each product's download and its existing AI coach — no need to re-upload anything.", related_name='in_one_time_offers', to='shop.product')),
                ('product', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_time_offer', to='shop.product')),
            ],
            options={
                'verbose_name': 'One-Time Offer',
                'verbose_name_plural': 'One-Time Offer',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
