# Generated by Django 5.2.9 on 2026-09-12 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('tools', '0002_rename_tools_str_user_tool_idx_tools_saved_user_id_cc54bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tools_newsletter_enabled',
            field=models.BooleanField(default=False, help_text="When ticked, an optional 'email me my results' box appears at the bottom of every FREE hosted tool for logged-out visitors (never on paid tools, never for a signed-in visitor — they get the save-to-dashboard box instead).", verbose_name='Show newsletter sign-up on free tools'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tools_newsletter_message',
            field=models.TextField(blank=True, default='', help_text='Optional supporting line shown under the newsletter box heading.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tools_newsletter_title',
            field=models.CharField(blank=True, default='', help_text='Heading for the newsletter box. Leave blank for a sensible default.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tools_saving_enabled',
            field=models.BooleanField(default=True, help_text='When ticked, a logged-in visitor sees a "Save to my dashboard" button under a tool (if that tool also has saving switched on) and can come back to their results later.', verbose_name='Let visitors save tool results to their dashboard'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hosted_tool',
            field=models.ForeignKey(blank=True, help_text="Optional: attach a Hosted Tool to sell it as this product. Only tools set to 'Paid' can be selected here. Buyers reach the live tool from their downloads area, and the tool's public page becomes purchase-only. Leave blank for a normal file download. The same tool can be linked from more than one product (e.g. price tiers).", limit_choices_to={'access': 'paid'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tools.hostedtool'),
        ),
    ]
