# Generated by Django 6.0 on 2025-12-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchased_download',
            field=models.ForeignKey(blank=True, help_text='The specific download variant the customer purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productdownload'),
        ),
        migrations.AlterField(
            model_name='productdownload',
            name='label',
            field=models.CharField(default='Add To Cart', help_text="Button text shown to the customer (e.g. 'Download PDF', 'Windows Version', 'Starter Pack')", max_length=100),
        ),
    ]
