# Generated by Django 5.2.9 on 2026-09-17 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sitesettings_tools_newsletter_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_solved', models.TextField(blank=True, help_text='The specific problem a buyer has that this product solves.', verbose_name='Problem this solves')),
                ('target_audience', models.TextField(blank=True, help_text="The specific kind of person this is for, not 'everyone'.", verbose_name="Who it's for")),
                ('differentiator', models.TextField(blank=True, help_text='What sets this apart from other ways to solve the same problem.', verbose_name='What makes it different')),
                ('search_keywords', models.CharField(blank=True, help_text='Comma-separated terms someone would search for before buying this.', max_length=500, verbose_name='Search terms')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Knowledge',
                'verbose_name_plural': 'Product Knowledge',
            },
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Question',
                'verbose_name_plural': 'Product Questions (FAQ)',
                'ordering': ['order'],
            },
        ),
    ]
