# Generated by Django 5.2.9 on 2026-08-16 09:33

import django.utils.timezone
from django.db import migrations, models


def backfill_display_date(apps, schema_editor):
    """Seed display_date from created_at so existing ordering is preserved."""
    Portfolio = apps.get_model("portfolio", "Portfolio")
    for project in Portfolio.objects.all():
        Portfolio.objects.filter(pk=project.pk).update(
            display_date=project.created_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-display_date', 'order'], 'verbose_name_plural': 'Portfolio Projects'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='display_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Controls where this project appears on the portfolio (most recent first). Edit this to reposition a project. Adjust the time to separate several projects added on the same day.'),
        ),
        migrations.RunPython(backfill_display_date, migrations.RunPython.noop),
    ]
