# Generated by Django 5.2.9 on 2026-08-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options_portfolio_display_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['order', '-display_date'], 'verbose_name_plural': 'Portfolio Projects'},
        ),
    ]
