# Generated by Django 5.2.9 on 2026-08-22 14:19

import django.db.models.deletion
import todianedev.storage
import tools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=2)),
                ('goal_text', models.CharField(max_length=200)),
                ('is_achieved', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['milestone', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(help_text='The Monday this week starts', unique=True)),
                ('week_number', models.PositiveIntegerField()),
                ('is_milestone', models.BooleanField(default=False)),
                ('milestone_label', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_posts_rewritten', models.PositiveIntegerField(default=0)),
                ('pinterest_pins', models.PositiveIntegerField(default=0)),
                ('youtube_audio', models.PositiveIntegerField(default=0)),
                ('substack_posts', models.PositiveIntegerField(default=0)),
                ('emails_added', models.PositiveIntegerField(default=0)),
                ('ga4_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('what_i_did', models.TextField(blank=True)),
                ('what_i_noticed', models.TextField(blank=True)),
                ('what_changed', models.TextField(blank=True)),
                ('went_well_wednesday', models.TextField(blank=True)),
                ('revenue_this_week', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('transactions', models.PositiveIntegerField(default=0)),
                ('email_list_total', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_date'],
            },
        ),
        migrations.CreateModel(
            name='HostedTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Used in the public URL: /tools/<slug>/ . Leave blank to auto-fill from the title.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short caption shown above the tool on its public page.')),
                ('link_text', models.CharField(blank=True, help_text="Optional. The clickable label for a link button shown at the top AND bottom of the tool's page (e.g. 'Back to the shop', 'Get the full guide'). Leave blank to hide the link.", max_length=120, verbose_name='URL name')),
                ('link_url', models.URLField(blank=True, help_text='Where the link button points. Only shown if both fields are filled.', max_length=500, verbose_name='URL link')),
                ('html_file', models.FileField(help_text='Upload the single .html file. Hit save and it goes live at the URL above.', storage=todianedev.storage.SecureFileStorage(), upload_to='hosted_tools/', validators=[tools.models.validate_html])),
                ('access', models.CharField(choices=[('free', 'Free — anyone can use it'), ('paid', 'Paid — only buyers can use it')], default='free', help_text="Free tools are public at /tools/<slug>/. Paid tools are unlocked only by buying a linked shop product (attach this tool to a Product in the shop, then it appears in the buyer's downloads area).", max_length=10)),
                ('published', models.BooleanField(default=True, help_text='Untick to take the tool offline without deleting it.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hosted Tool',
                'verbose_name_plural': 'Hosted Tools',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=2, unique=True)),
                ('reflection_text', models.TextField()),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AliveListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_living_it', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alive_list_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='ToolSavedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_slug', models.SlugField(help_text='Slug of the HostedTool that created this result.', max_length=200)),
                ('tool_title', models.CharField(blank=True, help_text='Human-readable tool name, captured at save time.', max_length=200)),
                ('label', models.CharField(help_text="Short name for this result, e.g. 'My top 3 values'.", max_length=300)),
                ('data', models.JSONField(default=dict, help_text='Arbitrary JSON payload from the tool.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_saved_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
