# Generated by Django 5.2.9 on 2026-09-12 08:23

import todianedev.storage
import tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedtoolresult',
            new_name='tools_saved_user_id_cc54bf_idx',
            old_name='tools_str_user_tool_idx',
        ),
        migrations.AlterField(
            model_name='hostedtool',
            name='html_file',
            field=models.FileField(help_text='Upload the single .html file. Hit save and it goes live at the URL above.', storage=todianedev.storage.SecureStorage(), upload_to='tools/', validators=[tools.models.validate_html]),
        ),
        migrations.AlterField(
            model_name='hostedtool',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional small thumbnail shown on the /tools/ list page. Max 1MB, 1200x1200px or smaller. Leave blank to show a plain card with no image.', null=True, storage=todianedev.storage.PublicStorage(), upload_to='tools/cards/', validators=[tools.models.validate_tool_image]),
        ),
    ]
